### ISSUE TITLE
winston-transport/legacy.js:18

### ISSUE THREAD

**Issue by dranreb38** [empierre/domoticz_gaspar#12]
Bonjour,

Maintenant que j'ai enfin des données sur le site (https://monespace.grdf.fr/monespace/particulier) et que j'ai enfin réussi à valider la connexion je rencontre une erreur à laquelle je ne sais pas comment résoudre. 

`/home/pi/domoticz/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/home/pi/domoticz/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/home/pi/domoticz/node_modules/winston/lib/winston/logger.js:345:11)
    at Object.winston.(anonymous function).args [as add] (/home/pi/domoticz/node_modules/winston/lib/winston.js:110:68)
    at Object.<anonymous> (/home/pi/domoticz/domoticz_gaspar/domoticz_gaspar.js:121:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
`
node v10.15.2
npm 6.13.4
 winston@3.2.1
Merci de votre aide

**Comment by empierre** [comment]
Quelle est la version de l'os ? Un buster ?

**Comment by dranreb38** [comment]
Bonjour Emmanuel

Oui sous Buster, Raspberry 3 B+

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by empierre** [comment]
duplicate of #13 

pas la bonne version de npm installée
