### ISSUE TITLE
plus de données depuis le 15/08??

### ISSUE THREAD

**Issue by dltrainou** [empierre/domoticz_gaspar#18]
bonjour
ce plugin fonctionnait correctement , mais sans rien changer, je n'ai plus de valeurs depuis le 15/08??
le req.sql s'arrete la
DELETE FROM 'Meter_Calendar' WHERE devicerowid=547 and date = '2020-08-15'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (547, '0', ........
UPDATE DeviceStatus SET lastupdate = '2020-08-16 20:30:00' WHERE id = 547;
sur le site, il y bien des valeurs affichées??
une idée? merci d'avance et bonne journée.

le log me donne erreur certificat??
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 187, in <module>
    main()
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 115, in main
    token = gaspar.login(USERNAME, PASSWORD)
  File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 97, in login
    session.get(LOGIN_BASE_URI + API_ENDPOINT_LOGIN, data=payload, allow_redirects=False)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

**Comment by biwizit** [comment]
Hello,

Yes, quite the same for me. It was OK until August 17th 6PM, and not OK since at least  August 18th 8AM.

My log:

```
2020-08-18 08:00:17,044 retrieving data...
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar_json.py", line 124, in main
    dtostr(today))
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar.py", line 148, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar.py", line 292, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-08-18 13:00:02,030 logging in as xxx@yyy.fr...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='monespace.grdf.fr', port=443): Max retries exceeded with url: /web/guest/monespace?p_p_id=EspacePerso_WAR_EPportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&_EspacePerso_WAR_EPportlet__jsfBridgeAjax=true&_EspacePerso_WAR_EPportlet__facesViewIdResource=%2Fviews%2FespacePerso%2FseconnecterEspaceViewMode.xhtml (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar_json.py", line 113, in main
    token = gaspar.login(USERNAME, PASSWORD)
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar.py", line 97, in login
    session.get(LOGIN_BASE_URI + API_ENDPOINT_LOGIN, data=payload, allow_redirects=False)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='monespace.grdf.fr', port=443): Max retries exceeded with url: /web/guest/monespace?p_p_id=EspacePerso_WAR_EPportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&_EspacePerso_WAR_EPportlet__jsfBridgeAjax=true&_EspacePerso_WAR_EPportlet__facesViewIdResource=%2Fviews%2FespacePerso%2FseconnecterEspaceViewMode.xhtml (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Comment by empierre** [comment]
I shod see how to avoid their Certificate verification...

**Comment by dltrainou** [comment]
thanks, merci d'avance. j'éspere qu'ils sont pas parti sur le mème processus de token que pour le linky???

**Comment by ProfBoc75** [comment]
Hello All,

J'ai mis un contournement ici : [Correction gaspar.py](https://github.com/empierre/domoticz_gaspar/issues/19#issuecomment-679162591)

**Comment by empierre** [comment]
Hello,

  commité la proposition de @profbox75

**Comment by empierre** [comment]
fixé à l'instant

**Comment by biwizit** [comment]
C'est tout bon, merci ! 

`2020-08-24 17:44:41,249 logging in as xxx@yyy.fr...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-08-24 17:44:52,948 logged in successfully!
2020-08-24 17:44:52,949 retrieving data...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-08-24 17:45:01,539 got data!
269,1498,2702,2996,3571,1592,2834,1073,863,201,119,85
09/2019,10/2019,11/2019,12/2019,01/2020,02/2020,03/2020,04/2020,05/2020,06/2020,07/2020,08/2020
5,4,2,2,2,7,4,6,2,4,10,4
Le 12/08/2020,Le 13/08/2020,Le 14/08/2020,Le 15/08/2020,Le 16/08/2020,Le 17/08/2020,Le 18/08/2020,Le 19/08/2020,Le 20/08/2020,Le 21/08/2020,Le 22/08/2020,Le 23/08/2020

`

**Comment by dltrainou** [comment]
toujours un pb avec le nouveau gaspar.py!!! 
une idée? merci d'avance (mes données sont a 0, est ce le pb?
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Addi$
  InsecureRequestWarning)
2020-08-25 07:35:02,350 logged in successfully!
2020-08-25 07:35:02,351 retrieving data...
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 187, in <module>
    main()
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 126, in main
    dtostr(today))
  File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 150, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 300, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by empierre** [comment]
Envoies moi le contenu de la page + une capture d'écran de :
https://monespace.grdf.fr/monespace/particulier/consommation/consommations
sur domoticz@e-nef.com

**Comment by dltrainou** [comment]
Bonjour

Consommation sur quelle base ? mois ? semaine ?

Merci

 

De : Emmanuel <notifications@github.com> 
Envoyé : mardi 25 août 2020 08:50
À : empierre/domoticz_gaspar <domoticz_gaspar@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [empierre/domoticz_gaspar] plus de données depuis le 15/08?? (#18)

 

Envoies moi le contenu de la page + une capture d'écran de :
https://monespace.grdf.fr/monespace/particulier/consommation/consommations
sur domoticz@e-nef.com

**Comment by dam9385** [comment]
Bonjour à tous,

Je permets de répondre suite au dernier commentaire, le site grdf est indisponible pour le moment (pour moi), voici l’aperçu de la page https://monespace.grdf.fr/monespace/particulier/consommation/consommations
![image](https://user-images.githubusercontent.com/70471134/91656950-6c9a6e00-eabd-11ea-93a2-44e31ec998d7.png)

L'erreur `AttributeError: 'NoneType' object has no attribute 'group'` est donc normale.

J’espère qu'ils vont pas tout changer et qu'on retrouvera nos relevés de conso :)
Merci pour le fix SSL en tout cas, c'est top.

Bon dimanche

**Comment by empierre** [comment]
Hello,

  J'ai rajouté un timeout infini, les appels passent du premier coup
maintenant même si le site est lent
