### ISSUE TITLE
days values non exported

### ISSUE THREAD

**Issue by pjuhel2** [empierre/domoticz_gaspar#21]
Bonjour,
Je viens d'installer le plugin. Merci!
Lorsqu'il arrive qu'il n'y a pas l'erreur 'NoneType' object has no attribute 'group', Le log enregistre:

2020-10-11 21:30:41,090 logged in successfully!
2020-10-11 21:30:41,091 retrieving data...
2020-10-11 21:30:50,642 got data!
2020-10-11 21:30:50,643 days values non exported

Les données affichées dans domoticz restent à zéro.
Quel peut être la source du problème?

**Comment by dltrainou** [comment]
e ne sais pas si ca a un rapport mais chez moi plus de données depuis le 7/10!! même pb que précédemment?
2020-10-12 17:36:42,587 logging in as xxxxx@free.fr...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
2020-10-12 17:36:50,377 logged in successfully!
2020-10-12 17:36:50,377 retrieving data...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWa$
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 187, in <module>
    main()
  File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 126, in main
    dtostr(today))
  File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 150, in get_data_per_$
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 300, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
