### ISSUE TITLE
Erreurs dans log et pas de données

### ISSUE THREAD

**Issue by Fredoberti11** [empierre/domoticz_gaspar#25]
Bonjour,
après exécution de domoticz_gaspar.sh , aucune donnée ne remonte et voici l'erreur de mon fichier log ;
2021-07-19 12:20:54,609 logged in successfully!
2021-07-19 12:20:54,609 retrieving data...
Traceback (most recent call last):
  File "/home/domoticz/domoticz/plugins/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/domoticz/domoticz/plugins/domoticz_gaspar/gaspar_json.py", line 124, in main
    dtostr(today))
  File "/home/domoticz/domoticz/plugins/domoticz_gaspar/gaspar.py", line 150, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/domoticz/domoticz/plugins/domoticz_gaspar/gaspar.py", line 305, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

tous les modules sont à jour et rien ne remonte.

**Comment by empierre** [comment]
Hello,

  Le message d'erreur dit juste qu'il n'a rien récupéré comme données.

sur le site gaspar, vois-tu des données, des graphes sur ton usage ?

**Comment by Fredoberti11** [comment]
Oui,
je me suis connecté sur le site de GRDF et je vois bien les données
