### ISSUE TITLE
Le plugin ne marche plus

### ISSUE THREAD

**Issue by djs45** [empierre/domoticz_gaspar#30]
Bonjour.
Je viens de me rendre compte que le plugin ne marche plus sur mon domoticz depuis quelques jours.
Pourriez vous me dire ce que vous en pensez ?
Merci beacuoup.

Voici le log : 

2021-12-09 14:00:03,870 logging in as xxxxxxx@hotmail.com...
Traceback (most recent call last):
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 113, in main
    token = gaspar.login(USERNAME, PASSWORD)
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 101, in login
    javaxvs2=parse_lxml(req.text)
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 61, in parse_lxml
    root = etree.fromstring(c)
  File "src/lxml/etree.pyx", line 3222, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 6
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8

**Comment by empierre** [comment]
il ne marchera plus, voir l'autre fil de discussion avec une proposition de remplacement
