### ISSUE TITLE
global JAVAVXS SyntaxError: name 'JAVAVXS' is used prior to global declaration

### ISSUE THREAD

**Issue by arawak-consulting** [empierre/domoticz_gaspar#7]
Bonjour
Je rencontre cette erreur mais impossible de la corriger :-(

**Comment by ganq76** [comment]
view this fork : https://github.com/aspichat/domoticz_gaspar/tree/aspichat-patch-1

**Comment by arawak-consulting** [comment]
Bonjour.

Il semble que cela fonctionne car les fichiers export_days_values.json
et export_months_values.json ont été générés malgré quelques erreurs :
1- la déclaration global JAVAVXS semble nécessaire juste après la
définition de la fonction _get_date en ligne 149 (def _get_data)
2- un message d'erreur apparaît lors de l’exécution du script alors que
j'ai bien installé le module winston (CentOS 7):
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/dbadmin/GRDF/domoticz_gaspar.js:20:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2018-12-26 18:55:10,478 logging in as xxx@xxxx.com...
2018-12-26 18:55:14,664 logged in successfully!
2018-12-26 18:55:14,664 retrieving data...
2018-12-26 18:55:29,553 got data!

**Comment by ganq76** [comment]
Bonjour, quelle est la version de winston ? Souvent, il faut downgrader

**Comment by empierre** [comment]
huh je ne sais pas, c'est celle de mydomoathome je pense...

sinon j'ai corrigé pas mal de choses dans mon dernier commit
