### ISSUE TITLE
error and strange thing in shell script

### ISSUE THREAD

**Issue by albebert** [empierre/domoticz_gaspar#8]
hello doesn't work for me : 

/opt/domoticz_gaspar/gaspar.py:199: SyntaxWarning: name 'JAVAVXS' is used prior to global declaration
  global JAVAVXS
2019-03-22 00:13:38,798 logging in as rahard.adrien@free.fr...
2019-03-22 00:13:45,515 logged in successfully!
2019-03-22 00:13:45,516 retrieving data...
Traceback (most recent call last):
  File "/opt/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/opt/domoticz_gaspar/gaspar_json.py", line 124, in main
    dtostr(today))
  File "/opt/domoticz_gaspar/gaspar.py", line 143, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/opt/domoticz_gaspar/gaspar.py", line 283, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

any idea ?

another thing, in the shell script you execute a sql on the domoticz.db, but pointing the db in : 
${HOME}"/domoticz/domoticz.db

but domoticz it's not necessary in the home directory ! (it's not a good pratice to do that)

i think that add the path of db in the .cfg is a good idea

**Comment by empierre** [comment]
fixed in latest version
